name: request_state
description: An alternative to flutter's built-in State class made specifically to deal with async http requests.
version: 0.1.0
repository: https://github.com/jakcharvat/request_state
homepage: https://github.com/jakcharvat/request_state/blob/master/README.md

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: