name: request_state
description: A new Flutter package project.
version: 0.0.1
author: Jakub Charvat <jakcharvat@gmail.com>
repository: https://github.com/jakcharvat/request_state

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: